### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by plexp** [techheavencz/thvn-web-frontend#17]
Analytics nezobrazují žádná data - je tam správně kód?

**Comment by jakubboucek** [comment]
Posílá se na id: `UA-112111982-1`, je to správně?

**Comment by plexp** [comment]
@jakubboucek Není... Je to nějaký jiný účet? @voborilovab

**Comment by jakubboucek** [comment]
Na Báru se neobracej, ta je v tom nevinně. Nezapoměň, že GA jsou tam přes [GTM](https://tagmanager.google.com/), které jsi nastavoval ty @plexp a nasazoval jsem je já.

**Comment by plexp** [comment]
To já vím, ale někdo to někde musel změnit, protože i z GTM ta data chodila

**Comment by jakubboucek** [comment]
OK, pak tedy, jak je to nastavené v [GTM](https://github.com/techheavencz/thvn-web-frontend/pull/5) a souhlasí GTM ID kontejneru: `GTM-WHCDM7N`?

Pokud to ID tady nesedí, tak někdo musel změnit nastavení GTM, což lze dohledat v jeho historii. Já tam přístup zřejmě nemám, tak nevím :-/

**Comment by plexp** [comment]
Ten GTM, co tam je není ten můj...

**Comment by jakubboucek** [comment]
You right, sh*t :-/

**Comment by jakubboucek** [comment]
Je to vydeployované na web. Potvrď prosím, že analytics už trackuje.

**Comment by plexp** [comment]
@jakubboucek funguje, díky
