### ISSUE TITLE
Outdated Readme

### ISSUE THREAD

**Issue by jakubboucek** [techheavencz/thvn-web-frontend#20]
In commit 99e20d5f0c38d9f68ec3faca612aba267a37323b (by @ondrej-merkun) is replaced `NPM` to `Yarn`.

But nothing of that is applied to `README.md`, that is now outdated. 

Please @ondrej-merkun, update the Readme to know how to prepare app to run.

**Comment by ondrej-merkun** [comment]
Never really _replaced_ `NPM` with `Yarn`. Either can be used as all dependencies are in `package.json`.

**Comment by jakubboucek** [comment]
As I know is very important use `lock` files, only `package.json` is lacking, because it define only requirements, but these are very tolerant to unspecifient differents between package versions and sub-packages.

In mentioned commit you create `yarn.lock`, that mean, now when someone use `npm install`, it made different devstack than `yarn install`.
